// features/employerJobs/styles/employerStyles.js
import { Dimensions, Platform, StyleSheet } from "react-native";
const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  // ... YOUR EXACT ORIGINAL STYLES
  container: { flex: 1, backgroundColor: "#0B0D1A" },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0B0D1A",
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "ios" ? 60 : 40,
    paddingBottom: 20,
  },
  welcomeText: { fontSize: 14, color: "#888" },
  userName: { fontSize: 24, fontWeight: "bold", color: "#fff", marginTop: 4 },
  userEmail: { fontSize: 13, color: "#666", marginTop: 2 },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 16,
    gap: 12,
    marginTop: 8,
  },
  statCard: {
    width: (width - 56) / 2,
    backgroundColor: "#131629",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#1E2240",
  },
  hiredCard: {
    width: width - 32,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  statNumber: { fontSize: 32, fontWeight: "bold" },
  statLabel: { fontSize: 12, color: "#888", marginTop: 4 },
  createBtn: {
    backgroundColor: "#7C3AED",
    marginHorizontal: 16,
    marginVertical: 16,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  createBtnText: { fontSize: 16, fontWeight: "bold", color: "#fff" },
  bottomNav: {
    flexDirection: "row",
    backgroundColor: "#0F1225",
    borderTopWidth: 1,
    borderTopColor: "#1E2240",
    paddingVertical: 12,
    paddingHorizontal: 8,
    marginTop: 16,
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
    borderRadius: 8,
  },
  navItemActive: { backgroundColor: "#7C3AED20" },
  navText: { fontSize: 12, color: "#888", fontWeight: "500" },
  navTextActive: { color: "#7C3AED", fontWeight: "bold" },
  searchContainer: {
    backgroundColor: "#131629",
    marginHorizontal: 16,
    marginBottom: 16,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1E2240",
  },
  searchInput: { paddingVertical: 12, color: "#fff", fontSize: 14 },
  filterScroll: {
    flexDirection: "row",
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  filterBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#131629",
    marginRight: 8,
    borderWidth: 1,
    borderColor: "#1E2240",
  },
  filterBtnActive: { backgroundColor: "#7C3AED", borderColor: "#7C3AED" },
  filterBtnText: { fontSize: 12, color: "#888" },
  filterBtnTextActive: { color: "#fff" },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 12,
  },
  sectionTitle: { fontSize: 18, fontWeight: "bold", color: "#fff" },
  seeAll: { fontSize: 13, color: "#7C3AED" },
  jobCard: {
    backgroundColor: "#131629",
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#1E2240",
    gap: 8,
  },
  jobTitle: { fontSize: 16, fontWeight: "bold", color: "#fff" },
  jobCompany: { fontSize: 13, color: "#888", marginTop: 2 },
  jobDetail: { fontSize: 12, color: "#888" },
  tagsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  tag: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#2A2E50",
  },
  tagText: { fontSize: 11, color: "#AAA" },
  skillsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  skillTag: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: "#7C3AED15",
  },
  skillText: { fontSize: 11, color: "#9B8EFF" },
  actionRow: {
    flexDirection: "row",
    gap: 20,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#1E2240",
  },
  editText: { color: "#9B8EFF", fontSize: 13 },
  deleteText: { color: "#FF4444", fontSize: 13 },
  appCard: {
    backgroundColor: "#131629",
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#1E2240",
    gap: 8,
  },
  appName: { fontSize: 15, fontWeight: "bold", color: "#fff" },
  appRole: { fontSize: 12, color: "#888", marginTop: 2 },
  appEmail: { fontSize: 12, color: "#888" },
  appPhone: { fontSize: 12, color: "#888" },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  statusText: { fontSize: 11, fontWeight: "bold" },
  coverBox: { backgroundColor: "#1A1D35", padding: 10, borderRadius: 10 },
  coverText: { fontSize: 12, color: "#AAA", fontStyle: "italic" },
  viewBtn: {
    backgroundColor: "#1E2240",
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 8,
  },
  viewBtnText: { color: "#9B8EFF", fontSize: 13, fontWeight: "600" },
  statusActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  statusAction: { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 16 },
  statusActionText: { fontSize: 11, fontWeight: "600" },
  profileTop: {
    alignItems: "center",
    paddingTop: 40,
    paddingBottom: 24,
    gap: 8,
  },
  profileAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#1A1D35",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#2A2E50",
  },
  profileAvatarText: { fontSize: 32, fontWeight: "bold", color: "#9B8EFF" },
  profileName: { fontSize: 20, fontWeight: "bold", color: "#fff" },
  profileEmail: { fontSize: 14, color: "#888" },
  profileBadge: {
    paddingHorizontal: 18,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#2A2E50",
  },
  profileBadgeText: { fontSize: 14, color: "#9B8EFF" },
  profileSection: { paddingHorizontal: 16, marginTop: 8, marginBottom: 30 },
  menuItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#131629",
    padding: 16,
    borderRadius: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#1E2240",
  },
  menuTitle: { fontSize: 15, fontWeight: "600", color: "#fff" },
  menuDesc: { fontSize: 12, color: "#888", marginTop: 2 },
  arrow: { fontSize: 18, color: "#666" },
  logoutButton: {
    backgroundColor: "#EF4444",
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 20,
    marginBottom: 30,
  },
  logoutButtonText: { color: "#fff", fontWeight: "bold", fontSize: 16 },
  emptyState: { alignItems: "center", paddingVertical: 60 },
  emptyTitle: { fontSize: 16, color: "#888" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.95)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#131629",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: height * 0.9,
    padding: 20,
    width: width,
    alignSelf: "center",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#1E2240",
  },
  modalTitle: { fontSize: 20, fontWeight: "bold", color: "#fff" },
  modalClose: { fontSize: 24, color: "#888", fontWeight: "bold" },
  input: {
    backgroundColor: "#1E2240",
    borderRadius: 12,
    padding: 14,
    color: "#fff",
    fontSize: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#2A2E50",
  },
  textArea: { height: 100, textAlignVertical: "top" },
  typeRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 12 },
  typeChip: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 24,
    backgroundColor: "#1E2240",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#2A2E50",
  },
  typeChipActive: { backgroundColor: "#7C3AED", borderColor: "#7C3AED" },
  typeChipText: { fontSize: 12, color: "#AAA" },
  typeChipTextActive: { color: "#fff" },
  modalFooter: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
    paddingBottom: 20,
  },
  cancelBtn: {
    flex: 1,
    backgroundColor: "#FF444420",
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
  },
  cancelBtnText: { color: "#FF4444", fontWeight: "bold" },
  submitBtn: {
    flex: 1,
    backgroundColor: "#7C3AED",
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
  },
  submitBtnText: { color: "#fff", fontWeight: "bold" },
  appDetailHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginBottom: 20,
  },
  appDetailAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#7C3AED20",
    justifyContent: "center",
    alignItems: "center",
  },
  appDetailAvatarText: { fontSize: 26, fontWeight: "bold", color: "#7C3AED" },
  appDetailName: { fontSize: 18, fontWeight: "bold", color: "#fff" },
  appDetailEmail: { fontSize: 13, color: "#888", marginTop: 2 },
  detailBox: { marginBottom: 20 },
  detailLabel: {
    fontSize: 12,
    color: "#7C3AED",
    marginBottom: 8,
    fontWeight: "600",
  },
  detailText: { fontSize: 14, color: "#DDD", marginBottom: 4 },
  coverFull: { backgroundColor: "#1E2240", padding: 14, borderRadius: 12 },
  coverFullText: { fontSize: 14, color: "#CCC", fontStyle: "italic" },
  confirmModal: {
    backgroundColor: "#131629",
    borderRadius: 20,
    padding: 24,
    width: width - 60,
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "#1E2240",
  },
  confirmTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 12,
    textAlign: "center",
  },
  confirmText: {
    fontSize: 14,
    color: "#888",
    marginBottom: 24,
    textAlign: "center",
  },
  confirmButtons: { flexDirection: "row", gap: 12 },
  confirmBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
  },
  cancelConfirmBtn: { backgroundColor: "#1E2240" },
  logoutConfirmBtn: { backgroundColor: "#EF4444" },
  cancelConfirmText: { color: "#888", fontWeight: "600" },
  logoutConfirmText: { color: "#fff", fontWeight: "600" },

  // ========== NEW STYLES FOR FULL DETAILS MODAL ==========

  // Modal Container
  modalContainer: {
    flex: 1,
    backgroundColor: "#0B0D1A",
  },

  // Full Detail Header
  fullDetailHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: Platform.OS === "ios" ? 56 : 20,
    backgroundColor: "#131629",
    borderBottomWidth: 1,
    borderBottomColor: "#1E2240",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  fullDetailBackBtn: {
    padding: 8,
  },
  fullDetailCloseBtn: {
    padding: 8,
  },
  fullDetailTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#fff",
  },
  fullDetailScroll: {
    flex: 1,
    padding: 16,
  },

  // Profile Header
  fullProfileHeader: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#131629",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#1E2240",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  fullProfileAvatar: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#7C3AED",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  fullProfileAvatarText: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#fff",
  },
  fullProfileInfo: {
    flex: 1,
  },
  fullProfileName: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 4,
  },
  fullProfileEmail: {
    fontSize: 14,
    color: "#888",
    marginBottom: 8,
  },
  fullProfileStatus: {
    flexDirection: "row",
  },

  // Status Badge Small
  statusBadgeSmall: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusTextSmall: {
    fontSize: 11,
    fontWeight: "bold",
  },

  // Sections
  fullSection: {
    backgroundColor: "#131629",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#1E2240",
  },
  fullSectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 12,
  },
  fullSubTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#7C3AED",
    marginTop: 12,
    marginBottom: 8,
  },

  // Info Grid
  fullInfoGrid: {
    gap: 12,
  },
  fullInfoItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#1E2240",
  },

  fullInfoLabel: {
    fontSize: 13,
    color: "#888",
    fontWeight: "500",
    flex: 1,
  },
  // Add these styles at the end of your employerStyles.js

  fullDetailScrollContent: {
    paddingBottom: 20,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 6,
  },
  fullInfoItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#1E2240",
  },
  fullInfoLabel: {
    fontSize: 13,
    color: "#888",
    fontWeight: "500",
    flex: 1,
  },
  fullInfoValue: {
    fontSize: 13,
    color: "#DDD",
    flex: 1.5,
    textAlign: "right",
  },
  fullInfoLink: {
    fontSize: 12,
    color: "#7C3AED",
    flex: 1.5,
    textAlign: "right",
    textDecorationLine: "underline",
  },
  fullInfoScore: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#10B981",
    textAlign: "right",
  },
  scoreContainer: {
    flex: 1.5,
  },
  scoreBar: {
    height: 4,
    backgroundColor: "#1E2240",
    borderRadius: 2,
    marginTop: 6,
    overflow: "hidden",
  },
  scoreFill: {
    height: "100%",
    backgroundColor: "#10B981",
    borderRadius: 2,
  },
  fullSkillsWrapper: {
    marginBottom: 12,
  },
  fullSkillsLabel: {
    fontSize: 12,
    color: "#888",
    marginBottom: 8,
  },
  fullSkillsList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  fullSkillChip: {
    backgroundColor: "#1E2240",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
  },
  fullSkillChipTop: {
    backgroundColor: "#7C3AED20",
    borderWidth: 1,
    borderColor: "#7C3AED",
  },
  fullSkillChipText: {
    fontSize: 11,
    color: "#AAA",
  },
  fullSkillChipTopText: {
    color: "#7C3AED",
    fontWeight: "500",
  },
  fullCoverBox: {
    backgroundColor: "#1E2240",
    padding: 12,
    borderRadius: 10,
  },
  fullCoverText: {
    fontSize: 13,
    color: "#CCC",
    lineHeight: 18,
  },
  fullStatusButtons: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  fullStatusBtn: {
    flex: 1,
    minWidth: (width - 60) / 2,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  fullStatusBtnActive: {
    borderWidth: 2,
    borderColor: "#fff",
  },
  fullStatusBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#fff",
  },
  fullSubTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#7C3AED",
    marginTop: 10,
    marginBottom: 8,
  },
  statusBadgeSmall: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  statusTextSmall: {
    fontSize: 10,
    fontWeight: "bold",
  },
  fullInfoValue: {
    fontSize: 13,
    color: "#DDD",
    flex: 2,
    textAlign: "right",
  },
  fullInfoLink: {
    fontSize: 13,
    color: "#7C3AED",
    flex: 2,
    textAlign: "right",
    textDecorationLine: "underline",
  },
  fullInfoScore: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#4CAF50",
    flex: 2,
    textAlign: "right",
  },
  fullInfoSuccess: {
    color: "#4CAF50",
    fontWeight: "600",
  },

  // Score Bar
  scoreContainer: {
    flex: 2,
    marginLeft: 12,
  },
  scoreBar: {
    height: 6,
    backgroundColor: "#1E2240",
    borderRadius: 3,
    marginTop: 8,
    overflow: "hidden",
  },
  scoreFill: {
    height: "100%",
    backgroundColor: "#4CAF50",
    borderRadius: 3,
  },

  // Skills
  fullSkillsContainer: {
    gap: 16,
  },
  fullSkillsWrapper: {
    gap: 8,
  },
  fullSkillsLabel: {
    fontSize: 13,
    color: "#888",
    fontWeight: "500",
  },
  fullSkillsList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  fullSkillChip: {
    backgroundColor: "#1E2240",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2A2E50",
  },
  fullSkillChipTop: {
    backgroundColor: "#7C3AED20",
    borderColor: "#7C3AED",
  },
  fullSkillChipText: {
    fontSize: 12,
    color: "#AAA",
  },
  fullSkillChipTopText: {
    color: "#7C3AED",
    fontWeight: "500",
  },

  // Cover Letter
  fullCoverBox: {
    backgroundColor: "#1E2240",
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#2A2E50",
  },
  fullCoverText: {
    fontSize: 14,
    color: "#CCC",
    fontStyle: "italic",
    lineHeight: 20,
  },

  // Status Buttons
  fullStatusButtons: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 8,
  },
  fullStatusBtn: {
    flex: 1,
    minWidth: (width - 72) / 3,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    opacity: 0.9,
  },
  fullStatusBtnActive: {
    opacity: 1,
    borderWidth: 2,
    borderColor: "#fff",
  },
  fullStatusBtnText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#fff",
  },

  // Footer
  fullFooter: {
    height: 40,
  },
});
